name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/node-telescope/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/node-telescope/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: npm ci
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Install package-specific dependencies
        run: |
          cd packages/node-telescope
          npm install
      - name: Lint packages
        run: npm run lint
      - name: Format packages
        run: npm run format
      - name: Build packages
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run npm audit in root
        run: npm audit
      - name: Run npm audit in node-telescope package
        run: |
          cd packages/node-telescope
          npm audit

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Run npm audit in node-telescope package
        run: |
          cd packages/node-telescope
          npm install
          npm audit --production
