name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/node-telescope/**'
      - 'packages/node-telescope-frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/node-telescope/**'
      - 'packages/node-telescope-frontend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: npm ci
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Check crucial files
        run: |
          if [ ! -f packages/node-telescope-frontend/public/index.html ]; then
            echo "index.html is missing in frontend public directory"
            exit 1
          fi
          if [ ! -f packages/node-telescope-frontend/src/index.tsx ]; then
            echo "index.tsx is missing in frontend src directory"
            exit 1
          fi
      - name: Install and build node-telescope
        run: |
          cd packages/node-telescope
          npm install
          npm run build
      - name: Install and build node-telescope-frontend
        run: |
          cd packages/node-telescope-frontend
          npm install
          npm run build
      - name: Lint packages
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Run npm audit in root
        run: npm audit
      - name: Run npm audit in node-telescope package
        run: |
          cd packages/node-telescope
          npm audit

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Run npm audit in node-telescope package
        run: |
          cd packages/node-telescope
          npm install
          npm audit --production
